apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  MYSQL_DATABASE_USER: "root"
  MYSQL_DATABASE_PASSWORD: "root"
  MYSQL_DATABASE_DB: "BucketList"
  MYSQL_DATABASE_HOST: "db-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
type: Opaque
data:
  MYSQL_DATABASE_USER: cm9vdA==  # base64 encoded username (e.g., root)
  MYSQL_DATABASE_PASSWORD: cm9vdA==  # base64 encoded password (e.g., root)
  MYSQL_DATABASE_DB: QnVja2V0TGlzdA==
  MYSQL_DATABASE_HOST: ZGI=
  MYSQL_ROOT_PASSWORD: cm9vdA==
